version: "3.7"
services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            # POSTGRES_DB: products
        ports:
            - 5432:5432
        volumes:
            #- ./database/data:/var/lib/postgresql/data
            - ./database/1-create_table.sql:/docker-entrypoint-initdb.d/1-create_table.sql
            - ./database/2-fill_table.sql:/docker-entrypoint-initdb.d/2-fill_table.sql

    store:
        build:
            context: ./images/go
        environment:
            DB_SCHEMA: go_store
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_HOST: postgres
        depends_on:
            - postgres
        ports:
            - 8000:8000
        volumes:
            - .:/go/src/go-webapp-store
